#!/usr/bin/env python3

from bs4 import BeautifulSoup
import sys

def extract_rss_link(html_content):
    soup = BeautifulSoup(html_content, 'html.parser')

    links = []
    rss_tags = soup.find_all('link', type='application/rss+xml')
    atom_tags = soup.find_all('link', type='application/atom+xml')
    for t in rss_tags + atom_tags:
        links.append(t['href'])
    try:
    	return sorted(links, key = len)[0]
    except IndexError:
    	return ''

print(extract_rss_link(sys.stdin.read()))

